<!-- TODO: write an actually decent csproj -->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>BigDebug</AssemblyName>
    <Product>Big Debug</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>BigDebug</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="../DearImGuiInjection/DearImGuiInjection.dll" />
    <Reference Include="../DearImGuiInjection/ImGui.NET.dll" />

    <Reference Include="/home/grub/.local/share/Steam/steamapps/common/Big Walk/BepInEx/interop/*.dll" />
  </ItemGroup>
</Project>
